# Generated by Django 5.2.9 on 2025-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=10, help_text='Time limit in minutes'),
        ),
    ]
