# Why do we need a Token Generator?
# We are creating a "One-Time Password" equivalent link. 
# default_token_generator creates a token based on:
# 1. User's primary key
# 2. User's hashed password
# 3. User's last login timestamp
# 4. Current timestamp
# If ANY of these change (e.g. user sets a password), the token becomes invalid.
from django.contrib.auth.tokens import default_token_generator

# URL Saftey:
# IDs can be integers (1, 2) or UUIDs (long strings). 
# We encode them to base64 bytes to ensure they travel safely over HTTP without weird character issues.
from django.utils.http import urlsafe_base64_encode

# Encoding Helper:
# Django internals require input to be in bytes before base64 encoding. 'force_bytes' handles string->bytes safely.
from django.utils.encoding import force_bytes

# The Mailman:
# send_mail is a synchronous wrapper. It connects to the SMTP server, authenticates, sends, and closes connection.
from django.core.mail import send_mail

# Reverse URL Resolution:
# Converts abstract view names ('activate_account') into actual URL paths ('/activate/...').
# Allows us to change URL structures without breaking email logic.
from django.urls import reverse

# Settings Access:
# Best practice: Do not hardcode credentials or email addresses. Read them from settings.py.
from django.conf import settings

def send_activation_email(user, request):
    """
    Orchestrates the account activation workflow via email.
    
    Why: 
    We don't want admins setting passwords manually (security risk). 
    We want the user to verify they own the email address.
    
    Mechanism: 
    Send a secret link that only the owner of that email inbox can access.
    """
    
    # Step 1: Create the crypto-token.
    # It acts as a digital signature verifying "This link was generated by us for this user at this time".
    token = default_token_generator.make_token(user)
    
    # Step 2: Obfuscate the User ID.
    # While not encryption, base64 encoding prevents accidental corruption of the ID in URL bars.
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    
    # Step 3: Construct relative path.
    # e.g., /activate/NA/55-fd3.../
    activation_url = reverse('activate_account', kwargs={'uidb64': uid, 'token': token})
    
    # Step 4: Make it absolute.
    # Emails open in a new context (Mail App, Gmail). They don't know "localhost" or your domain.
    # request.build_absolute_uri prepends 'https://example.com' based on the request that triggered this.
    link = request.build_absolute_uri(activation_url)
    
    # Step 5: Draft the email.
    subject = 'Set your password for Quiz App'
    message = f'Hello {user.username},\n\nPlease click the link below to set your password and activate your account:\n\n{link}\n\nThank you!'
    
    # Checks who is sending. Defined in settings.py to keep it central.
    from_email = settings.EMAIL_HOST_USER
    
    recipient_list = [user.email]
    
    # Step 6: Dispatch.
    # fail_silently=False: We WANT to know if the email fails (e.g. wrong SMTP password), 
    # so the app crashes and tells the admin "Email not sent", rather than failing silently.
    send_mail(
        subject,
        message,
        from_email,
        recipient_list,
        fail_silently=False,
    )
